/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://p3ussqec6bgsfdnr6dqt3hzkp4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-mz6qmnuv4bhohcbpprsodznuoq",
    "aws_cognito_identity_pool_id": "us-east-1:5b2bb643-8696-4ffe-b41a-720c5be4f30f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_jp6SDdWcN",
    "aws_user_pools_web_client_id": "2kjc4ekcc3lm251toks10am5e2",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
